import type { Project } from '@/lib/types';

export const adaptiveBeta: Project = {
  slug: 'adaptive-beta',
  name: 'AdaptiveBeta',
  wordmark: 'AdaptiveBeta',
  subtitle: 'Regime-Aware Dynamic Beta Forecasting & Portfolio Construction',
  hook: 'Beta isn\u2019t constant. This forecasts when it breaks — and cut portfolio drawdown by more than half.',
  summary:
    'A machine-learning risk overlay for Indian equities that forecasts beta instability, routes portfolio construction through an HMM regime classifier into three convex optimisers, and rebalances only when instability is predicted to spike. Walk-forward validated out-of-sample with transaction costs.',
  domainLine: 'Quantitative finance · Time-series forecasting · Convex optimisation',
  categories: ['Machine Learning', 'Quantitative ML', 'Time Series', 'MLOps'],
  period: 'Jan 2026 — Apr 2026',
  role: 'Sole author — end to end. M.Tech AI & ML capstone.',
  status: 'Research project · code available',
  statusTone: 'benchmark',
  repo: 'https://github.com/DAISHINKAN7/FinTech_AdaptiveBeta',
  scale: '~11,300 lines of Python + ~4,850 lines of TypeScript/React',
  headline: {
    value: '−17.36%',
    label: 'maximum drawdown, against −38.44% for the index',
    note: 'Walk-forward out-of-sample, transaction costs included',
    prov: 'verified',
  },
  cardMetrics: [
    { value: '−17.4%', label: 'max drawdown vs −38.4% index', prov: 'verified' },
    { value: '4 of 9', label: 'risk metrics ranked #1 of 6 strategies', prov: 'verified' },
    { value: '2,744', label: 'trading days modelled', prov: 'verified' },
    { value: '0.0391', label: 'signal-model MAE', prov: 'verified' },
  ],
  tech: ['Python', 'XGBoost', 'PyTorch', 'CVXPY', 'SHAP', 'hmmlearn', 'Next.js'],
  techGrouped: [
    { group: 'Core', items: ['NumPy', 'pandas', 'SciPy', 'scikit-learn'] },
    { group: 'Models', items: ['XGBoost 2.0', 'PyTorch 2.1 (LSTM)', 'SHAP', 'hmmlearn', 'pykalman'] },
    { group: 'Optimisation', items: ['CVXPY', 'PyPortfolioOpt', 'riskfolio-lib', 'QuantStats', 'Ledoit-Wolf shrinkage'] },
    { group: 'Visualisation', items: ['Matplotlib', 'Seaborn', 'Plotly'] },
    { group: 'Interfaces', items: ['Plotly Dash', 'Streamlit', 'Next.js 14', 'React 18', 'TypeScript 5.5', 'Recharts'] },
  ],
  glance: [
    { k: 'Problem', v: 'Beta is the most-used number in portfolio construction, and almost everyone treats it as a constant. It is not — and the divergence between intended and actual exposure is worst precisely during crises.' },
    { k: 'The reframe', v: 'Don\u2019t predict beta. Predict beta volatility — the instability of the exposure itself. Returns are famously hard to forecast, but instability clusters, so it is genuinely forecastable.' },
    { k: 'Universe', v: '49 NIFTY-50 constituents, 2015-01-02 → 2026-02-23, 2,744 trading days' },
    { k: 'Signal model', v: 'XGBoost — MAE 0.0391, 76.5% directional accuracy on 20-day-ahead beta volatility' },
    { k: 'Decision layer', v: 'VIX override → frozen betavol threshold → HOLD. 59.6% of days require no trade and pay no cost.' },
    { k: 'Validation', v: '3-year train → 1-year test → annual roll, strictly chronological, 8 bps round-trip costs charged on turnover' },
  ],
  heroDiagram: 'beta-layers',
  accentIndex: 2,
  related: ['astroguard', 'eco-rewind'],
  sections: [
    {
      id: 'problem',
      nav: 'Problem',
      title: 'CAPM assumes each of these is a single point',
      blocks: [
        {
          type: 'lede',
          text: 'Beta measures how sensitive a stock is to the market. Every mean-variance optimiser, every risk model and every hedge ratio depends on it — and almost everyone treats it as a constant.',
        },
        {
          type: 'prose',
          text: [
            'It drifts with market regimes, macro shocks and sector rotation. When a beta estimate goes stale, actual risk exposure diverges from intended risk exposure, and the divergence is worst precisely during dislocations, when it matters most.',
            'The chart below is 60-day rolling OLS beta on log returns against NIFTY 50, computed directly from the project\u2019s own price data over 2015–2026. Every bar is the range a single stock\u2019s beta actually travelled.',
          ],
        },
        { type: 'chart', id: 'beta-range', caption: 'Beta range travelled, 2015–2026. CAPM assumes each of these bars is a single point — so every bar is the error.', prov: 'verified' },
        {
          type: 'definitions',
          items: [
            {
              term: 'RELIANCE through the COVID crash',
              body: 'Over Nov 2019 → Jun 2020, RELIANCE.NS\u2019s rolling 60-day beta ran from 0.28 to 1.68. A portfolio built on the January estimate was carrying roughly six times the intended exposure by April.',
            },
            {
              term: 'Portfolio-level drift',
              body: 'An equal-weight book of the 49 constituents nominally targeting β = 0.85 actually drifts between 0.74 and 1.12 over 2015–2026 — up to 32% more market exposure than intended, with the excess arriving during dislocations.',
            },
          ],
        },
      ],
    },
    {
      id: 'insight',
      nav: 'The insight',
      title: 'The reframe that makes it work',
      blocks: [
        {
          type: 'quote',
          text: 'You don\u2019t need to predict beta. You need to predict beta volatility — the instability of the exposure itself.',
        },
        {
          type: 'prose',
          text: [
            'Returns are famously hard to forecast. But instability clusters, the same way volatility clusters in classical finance. So beta-volatility is genuinely forecastable, and knowing it tells you when your risk model is about to be wrong.',
            'Instead of rebalancing on a calendar — monthly, quarterly, arbitrary, expensive and blind to stress — AdaptiveBeta rebalances only when a model predicts beta instability is about to spike. The rest of the time it holds, and pays nothing.',
            'The project\u2019s own SHAP analysis confirms the premise empirically rather than assuming it: the three strongest predictors of future beta-volatility are all past beta-volatility measures. The model discovered the clustering; it was never told about it.',
          ],
        },
      ],
    },
    {
      id: 'architecture',
      nav: 'Architecture',
      title: 'Six layers, strictly ordered',
      blocks: [
        { type: 'diagram', id: 'beta-layers', caption: 'Data feeds into a 42-feature engine, four model families compete on one task, and a strict-priority decision layer routes into three convex optimisers before walk-forward validation.' },
        {
          type: 'table',
          caption: 'Data layer — twelve feeds, with NIFTY 50 as the master trading calendar',
          prov: 'verified',
          head: ['Category', 'Sources'],
          rows: [
            ['Equities', '49 NIFTY-50 constituents, daily OHLCV'],
            ['Market', 'NIFTY 50 index, India VIX'],
            ['Sector', 'NIFTY Bank, NIFTY IT, NIFTY FMCG'],
            ['Macro', 'USD-INR, WTI crude, RBI repo rate, 91-day T-bill yield'],
            ['Flows', 'FII net investment, DII net investment (monthly)'],
          ],
        },
        {
          type: 'prose',
          text: [
            'TMPV.NS is deliberately excluded from the config\u2019s 50 tickers — it has only 87 rows post-demerger, from October 2025. The feature engine emits a stacked panel of 118,719 rows × 44 columns (49 stocks × 2,423 valid dates) across eight feature groups, plus a separate market-level feature matrix shared across all stocks. The prediction target is 60-day rolling beta-volatility shifted forward 20 trading days.',
          ],
        },
        {
          type: 'table',
          caption: 'Eight feature groups, 42 features',
          prov: 'verified',
          head: ['Group', 'Features'],
          rows: [
            ['Beta dynamics', '30/60/120d rolling OLS beta; beta-volatility at each window; beta_60_30_spread; betavol_trend'],
            ['Volatility', 'India VIX level, 5d change, 20d change, z-score, above-25 flag; market vol 20d/60d'],
            ['Macro', 'USD-INR 5d change and 20d vol; crude 5d change and 20d vol'],
            ['Rates', 'RBI repo rate; 91-day T-bill; rate_spread'],
            ['Market', 'NIFTY 5d/20d return; realised vol'],
            ['Sector', 'Bank/IT/FMCG 10d momentum; bank_vs_nifty spread'],
            ['Flows', 'fii_net, dii_net, combined_flow, fii_dii_ratio'],
            ['Stock-specific', '21/63/126/252d momentum; RSI-14; MA-200 distance; realised vol 20d; stock_vs_mkt'],
          ],
        },
      ],
    },
    {
      id: 'models',
      nav: 'Models',
      title: 'Four families, one identical task',
      kicker: 'Every model is benchmarked on the same forward-looking target: 20-day-ahead beta volatility.',
      blocks: [
        { type: 'chart', id: 'beta-models', caption: 'Mean absolute error on 20-day-ahead beta volatility. Lower is better.', prov: 'verified' },
        {
          type: 'table',
          caption: 'Model comparison',
          prov: 'verified',
          head: ['Model', 'MAE', 'Directional accuracy', 'Role'],
          num: [1, 2],
          emphasis: [0],
          rows: [
            ['XGBoost + SHAP', '0.0391', '76.5%', 'Production signal model'],
            ['Static 60d rolling OLS', '0.0477', '—', 'Classical baseline'],
            ['LSTM (2 × 128 hidden)', '0.0661', '50.4%', 'Deep-learning baseline — negative result'],
            ['Kalman filter (state-space EM)', '0.0749', '—', 'Alternative time-varying beta'],
            ['Gaussian HMM (3-state)', '—', '—', 'Regime classifier (different task)'],
          ],
        },
        {
          type: 'callout',
          tone: 'insight',
          title: 'The LSTM lost, and that is a result',
          body: '50.4% directional accuracy is a coin flip. The diagnosis: with a Huber objective on a small, noisy, low-signal-to-noise financial panel, the network converged to predicting the conditional mean rather than learning the dynamics. Gradient boosting on well-engineered features beat it by 41% on MAE. It was a controlled comparison, correctly diagnosed, and the simpler model shipped. 230,785 parameters, AdamW at 1e-3 with ReduceLROnPlateau, gradient clipping at 1.0, sequence length 30, DataLoader shuffling explicitly disabled to preserve temporal order, early stopping triggered at epoch 12.',
        },
        { type: 'chart', id: 'beta-shap', caption: 'Top SHAP feature attributions for the XGBoost signal model. The three strongest predictors are all past beta-volatility measures.', prov: 'verified' },
        {
          type: 'prose',
          text: [
            'Two narrative points fall out of the attribution. First, the top three features are all beta-volatility measures, which means instability clusters — the strategy\u2019s empirical foundation, discovered by the model rather than assumed. Second, the highest-ranked non-beta feature is combined_flow, the FII+DII activity series, which is a genuinely India-specific signal that a generic US-equity model would never surface.',
          ],
        },
      ],
    },
    {
      id: 'decision',
      nav: 'Decision layer',
      title: 'ML owns the ambiguous days; hard rules own the tail',
      blocks: [
        { type: 'diagram', id: 'beta-decision', caption: 'A strict priority cascade evaluated daily. The VIX override is checked before the model is consulted at all.' },
        {
          type: 'prose',
          text: [
            'The betavol threshold of 0.1794 is the 70th percentile of XGBoost predictions on training data only, then frozen into signal_config.json. It is never re-fitted on test data. The VIX override at 22.0 exists because you do not want a statistical model deciding your fate in a genuine panic.',
          ],
        },
        {
          type: 'table',
          caption: 'Signal distribution across 1,719 signal days',
          prov: 'verified',
          head: ['Signal', 'Count', 'Frequency', 'Meaning'],
          num: [1, 2],
          rows: [
            ['HOLD', '1,025', '59.6%', 'No trade, no cost'],
            ['REBALANCE', '463', '26.9%', 'Regime-routed optimisation'],
            ['MIN_VARIANCE', '231', '13.4%', 'Defensive override'],
          ],
        },
        {
          type: 'table',
          caption: 'On a REBALANCE signal, the HMM regime picks the optimiser',
          prov: 'verified',
          head: ['Regime', 'Optimiser', 'Rationale'],
          rows: [
            ['Bull', 'max_sharpe_beta_constrained (β band ≈ 0.85)', 'Maximise risk-adjusted return with exposure capped'],
            ['Bear', 'min_variance', 'Capital protection'],
            ['Transition', 'risk_parity', 'Equal risk contribution'],
            ['Any, on VIX override', 'min_variance', 'Defensive, model bypassed'],
          ],
        },
        {
          type: 'table',
          caption: 'Constraints applied to every optimisation',
          prov: 'verified',
          head: ['Constraint', 'Value', 'Why'],
          num: [1],
          rows: [
            ['Max single-name weight', '15%', 'Idiosyncratic blow-up protection'],
            ['Min position weight', '1%', 'Removes unimplementable dust positions'],
            ['Max sector weight', '35%', 'Eight sector groups — prevents an accidental all-financials book'],
            ['Portfolio beta target', '≈0.85', 'Exposure is targeted, not inherited'],
            ['Covariance estimator', 'Ledoit-Wolf', '49 assets on short windows makes sample covariance ill-conditioned'],
          ],
        },
      ],
    },
    {
      id: 'results',
      nav: 'Results',
      title: 'Six strategies, one walk-forward backtest',
      kicker: 'Out-of-sample 2022-01-03 → 2026-01-23. 3-year train → 1-year test → annual roll, strictly chronological, 8 bps round-trip costs charged on turnover.',
      blocks: [
        { type: 'chart', id: 'beta-riskreturn', caption: 'Risk against return for all six strategies. AdaptiveBeta sits furthest left — nothing else is in that volatility band.', prov: 'verified' },
        {
          type: 'table',
          caption: 'Main scoreboard, from results/performance_metrics.csv',
          prov: 'verified',
          head: ['Strategy', 'CAGR', 'Sharpe', 'Sortino', 'Max DD', 'Calmar', 'Vol', 'Alpha', 'β'],
          num: [1, 2, 3, 4, 5, 6, 7, 8],
          emphasis: [0],
          rows: [
            ['AdaptiveBeta', '9.24%', '0.785', '1.047', '−17.36%', '0.532', '11.26%', '+4.24%', '0.40'],
            ['Static CAPM MVO', '11.38%', '0.587', '0.716', '−35.33%', '0.322', '18.35%', '+1.19%', '0.836'],
            ['Kalman-β MVO', '10.92%', '0.561', '0.676', '−35.44%', '0.308', '18.48%', '+0.58%', '0.852'],
            ['Equal Weight', '15.86%', '0.864', '0.992', '−38.23%', '0.415', '17.04%', '+3.85%', '0.948'],
            ['Buy & Hold NIFTY-50', '12.16%', '0.668', '0.781', '−38.44%', '0.316', '17.19%', '0.00%', '1.000'],
            ['Momentum-Quality', '17.47%', '0.893', '1.028', '−38.51%', '0.454', '18.03%', '+4.90%', '0.921'],
          ],
        },
        {
          type: 'callout',
          tone: 'caution',
          title: 'AdaptiveBeta has the lowest CAGR of the six — and that is the point',
          body: 'It runs at a market beta of 0.40, structurally ~60% less exposed to the index than every benchmark. Across a 2022–2026 window in which Indian equities generally rose, any defensive strategy trails a long-only book on raw return. That is arithmetic, not underperformance. Momentum-Quality also ran over a longer 2,707-day window against the others\u2019 1,964, so its total return is not directly comparable.',
        },
        {
          type: 'table',
          caption: 'The trade, versus Buy & Hold NIFTY-50',
          prov: 'verified',
          head: ['', 'Δ'],
          num: [1],
          rows: [
            ['CAGR given up', '−2.9 pts (9.24% vs 12.16%)'],
            ['Max drawdown avoided', '−21.1 pts (−17.36% vs −38.44%)'],
            ['Volatility removed', '−5.9 pts (11.26% vs 17.19%)'],
            ['Sortino gained', '+34% (1.047 vs 0.781)'],
            ['Calmar gained', '+68% (0.532 vs 0.316)'],
            ['Alpha generated', '+4.24% annualised at β = 0.40'],
          ],
        },
        {
          type: 'quote',
          text: 'Give up 2.9 points of return; remove 21 points of drawdown. An 11.26%-vol strategy can be levered toward benchmark volatility — a −38% drawdown cannot be un-levered after the fact.',
        },
      ],
    },
    {
      id: 'stress',
      nav: 'Stress tests',
      title: 'Four crises',
      blocks: [
        { type: 'chart', id: 'beta-stress', caption: 'Maximum drawdown during four stress windows. AdaptiveBeta records the smallest drawdown in three of four.', prov: 'verified' },
        {
          type: 'table',
          caption: 'Stress event analysis, from results/stress_analysis.csv',
          prov: 'verified',
          head: ['Event', 'Metric', 'AdaptiveBeta', 'Static MVO', 'Equal Wt', 'NIFTY-50'],
          num: [2, 3, 4, 5],
          rows: [
            ['COVID Crash (Feb–May 2020)', 'Cum. return', '−7.18%', '−10.42%', '−18.94%', '−17.57%'],
            ['', 'Max drawdown', '−8.97%', '−35.33%', '−37.63%', '−37.63%'],
            ['ADANI Crisis (Jan–Mar 2023)', 'Cum. return', '−6.66%', '−10.19%', '−6.66%', '−6.33%'],
            ['', 'Max drawdown', '−5.87%', '−13.71%', '−5.87%', '−5.90%'],
            ['2018 Rate Hike (Sep–Nov 2018)', 'Cum. return', '−7.51%', '−9.61%', '−7.51%', '−6.88%'],
            ['', 'Max drawdown', '−12.86%', '−14.33%', '−12.86%', '−13.45%'],
            ['IL&FS Crisis (Aug–Oct 2018)', 'Cum. return', '−6.01%', '−7.91%', '−6.01%', '−8.54%'],
            ['', 'Max drawdown', '−13.54%', '−15.85%', '−13.54%', '−14.55%'],
          ],
        },
        {
          type: 'callout',
          tone: 'insight',
          title: '−8.97% against −35.33% through COVID',
          body: 'A 26-point differential against standard mean-variance optimisation in the worst equity event of the decade. The mechanism was the VIX override firing and min-variance mode engaging during the crash — not beta forecasting the crash. That distinction matters, and it is made explicit below.',
        },
      ],
    },
    {
      id: 'rigour',
      nav: 'Rigour',
      title: 'The methodology checklist',
      kicker: 'This is what separates the project from a notebook.',
      blocks: [
        {
          type: 'table',
          caption: 'Methodological practices, all verified in source',
          prov: 'verified',
          head: ['Practice', 'Detail'],
          rows: [
            ['Walk-forward cross-validation', '3y train → 1y test → annual roll; retrained per window; never sees its test year'],
            ['Zero lookahead', 'Strictly chronological splits, series never shuffled, targets forward-shifted 20 days'],
            ['Costs charged', '8 bps round-trip (5 bps brokerage + 3 bps slippage) on turnover at every rebalance'],
            ['Threshold frozen', 'Q70 = 0.1794 calibrated on training predictions only, then locked'],
            ['Scaler fit on train only', 'StandardScaler fitted on train, applied to test — no distributional leakage'],
            ['Shrinkage covariance', 'Ledoit-Wolf on all 49×49 estimates'],
            ['Survivorship handled', 'TMPV.NS excluded; HDFCLIFE and SBILIFE pre-IPO windows explicitly zero-return, not silently filled'],
            ['Data quirks documented', "WTI's negative 2020-04-20 print clipped to 0; monthly FII/DII flows forward-filled with the ≤1-month lag stated openly"],
            ['Reproducible', 'All seeds fixed at 42; device auto-detection CUDA → MPS → CPU'],
            ['Six benchmarks, not one', 'Including two that beat it on CAGR — reported, not hidden'],
            ['Graceful degradation', 'Macro/flow/sector feeds are optional; the pipeline drops those feature groups with a warning rather than crashing'],
          ],
        },
      ],
    },
    {
      id: 'limitations',
      nav: 'Limitations',
      title: 'Including one claim that was tested and found false',
      blocks: [
        {
          type: 'callout',
          tone: 'caution',
          title: 'A retracted claim: beta does not lead price',
          body: 'An earlier version of this project stated that during the 2018 IL&FS crisis, NBFC sector betas surged weeks before the equity selloff. That was tested directly against the project\u2019s own price data and it is false. Rolling beta is a backward-looking window, so it mechanically lags: BAJFINANCE\u2019s beta peaked 2018-10-24 against a price peak of 2018-08-29; BAJAJFINSV 2018-10-11 vs 2018-08-21; AXISBANK 2018-09-03 vs 2018-08-28; SBIN 2018-09-04 vs 2018-08-09. Four of five lag. The honest framing is that AdaptiveBeta is a fast-reacting risk overlay, not a crisis predictor — and that framing survives scrutiny, which the original does not.',
        },
        {
          type: 'limitations',
          items: [
            {
              severity: 'high',
              title: 'Long-only, no leverage',
              detail: 'The risk-adjusted edge does not translate into absolute return without leverage, which is why the CAGR trails.',
              fix: 'Vol-target AdaptiveBeta up to benchmark volatility, where an 11.26%-vol strategy at β = 0.40 becomes directly comparable.',
            },
            {
              severity: 'high',
              title: 'Single market, single universe',
              detail: 'NIFTY-50 constituents only. Cross-market generalisation is untested.',
              fix: 'Re-run the full pipeline on an S&P 500 or STOXX universe with the same protocol.',
            },
            {
              severity: 'medium',
              title: 'Monthly FII/DII flows forward-filled to daily',
              detail: 'Up to a one-month information lag on that feature group — and combined_flow is the highest-ranked non-beta feature.',
              fix: 'Source higher-frequency flow data, or model the lag explicitly.',
            },
            {
              severity: 'medium',
              title: 'Close-price execution assumed',
              detail: 'No intraday microstructure or partial-fill modelling, and the fixed 8 bps cost model does not scale with order size or liquidity conditions.',
              fix: 'A liquidity-aware cost model keyed to ADV and order size.',
            },
            {
              severity: 'medium',
              title: 'Regime labels are unsupervised',
              detail: 'HMM states are interpreted post-hoc by sorting on mean market return, not validated against an external regime taxonomy.',
              fix: 'Score the labels against a published business-cycle or volatility-regime dataset.',
            },
            {
              severity: 'low',
              title: 'One optimiser diagnostic is easy to misread',
              detail: 'The max-Sharpe mode reports a 60.83% expected return and Sharpe 3.13 at a single date. Those are in-sample optimiser objective values computed from historical mean returns — classic Markowitz estimation-error inflation, not realised performance. They are excluded from every result on this page.',
              fix: 'Report optimiser objectives only alongside their realised counterparts.',
            },
          ],
        },
      ],
    },
  ],
};
